apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-blog
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spa-blog
  template:
    metadata:
      labels:
        app: spa-blog
    spec:
      containers:
      - name: spa-blog
        env:
          - name: DB_HOST
            value: database
        image: iankts/simple-blog:{{TAG}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: spa-blog
spec:
  selector:
    app: spa-blog
  ports:
  - port: 80
    targetPort: 3000
    # nodePort: 30000
    # protocol: TCP
  type: LoadBalancer

